
services:
  db:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: janaron
      POSTGRES_PASSWORD: aaronjaan
      POSTGRES_DB: scherzerrabardb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "35432:5432"

volumes:
  pgdata: